### ISSUE TITLE
이거.. 채널없으면 안되겠는데요. 여러개 동시에 리퀘스트가 오면 딕셔너리에 동시 라이팅 되면서 문제 발생.

### ISSUE THREAD

**Issue by zironycho** [sangwonl/qnsqnd#1]
https://github.com/sangwonl/qnsqnd/blob/a102f83526fedd0fb4edae7e3f18cdf58db73668/pkg/core/server.go#L111

**Comment by sangwonl** [comment]
@zironycho 헐? map 에 각각 다른 key 로 넣는데 에러 생기나요? map이 goroutine safe 하지 않은가보네요?

**Comment by sangwonl** [comment]
https://github.com/sangwonl/qnsqnd/pull/2

@zironycho 이거 재현되는지 한번 봐주실래요? 재현 경로도 한번 알려주시구요.

**Comment by sangwonl** [comment]
재현경로 확실하지 않음.
로드 테스트 하면서 이슈 재현되면 그때 다시 open 하기로..
